services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"     # AMQP port
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  producer:
    build: ./testing/message_producer
    depends_on:
      - rabbitmq

  consumer:
    build: ./testing/message_consumer
    depends_on:
      - rabbitmq
