name: Python CI with Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  stl_generation_ci:
    runs-on: ubuntu-latest  # or 'macos-latest' or 'windows-latest'

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # You can adjust this version if needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    # Step 4: Install pre-commit
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    # Step 5: Run pre-commit hooks (black, flake8, pytest)
    - name: Run pre-commit hooks
      run: |
        cd services/stl_generation
        pre-commit run --files services/stl_generation

    # Step 6: Run tests with pytest
    - name: Run pytest
      run: |
        cd services/stl_generation
        pytest .  


  web_app_ci:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # You can adjust this version if needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    # Step 4: Install pre-commit
    - name: Install pre-commit
      run: |
        pip install pre-commit
        pre-commit install

    # Step 5: Run pre-commit hooks (black, flake8, pytest)
    - name: Run pre-commit hooks
      run: |
        cd services/web_app
        pre-commit run --files services/web_app

    # Step 6: Run tests with pytest
    - name: Run pytest
      run: |
        cd services/web_app
        pytest  .
  
